[package]
name = "c2rust-build"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
build = "build.rs"

[[bin]]
path = "main.rs"
name = "cbordump-rs"

#[lib]
#path = "lib.rs"
#crate-type = "staticlib"

[build-dependencies]
cc = "1.0"
